fps = 40
GREEN = (0, 255, 0)

GARDEN_SIZE = [10, 10]
GRID_SIZE = 64
MOVE_SIZE = GRID_SIZE / 8
SCREEN_SIZE = [GARDEN_SIZE[0] * GRID_SIZE, GARDEN_SIZE[1] * GRID_SIZE]
N_ELEMS = 6

ANIMATION_SPEED = 5

# Keys
LEFT = 0
RIGHT = 1
UP = 2
DOWN = 3
